### PR TITLE
My Portfolio: Adding Contact Form Section 

### PR DESCRIPTION
**Pull request by DanielAD10**
PR Description

Project Name: My Portfolio
Tech: Built with HTML, CSS

In this PR,

Added form section in index.html
Styled form section
Modified README.md file

Thank you for reviewing my code 🙇‍♂️

### CODE REVIEW

**Review by LionRouge1 — CHANGES_REQUESTED** [review]
Hi @DanielAD10 & @rcniyigena, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

almost

## Highlights
- Good PR
- Good commit
- All linters passed

## Required Changes ♻️
- [ ] You need to build the contact form section for this milestone. Therefore kindly implement the "contact form" section as requested in the project requirement.
Screenshot from 2023-05-11 09-44-39

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by DanielAD10** [comment]
Hello @LionRouge1, I'm really thank you for reviewing my code. I want to explain my contact form. I did the contact form as the Figma template that I chose. So I don't understand what you want me to do. Do I change the text to "Contact form" like that?

The picture below is the contact form in the template that I choose
Screenshot (342)

**Comment by LionRouge1** [comment]
Hi @DanielAD10, sorry for the delay
Screenshot from 2023-05-11 12-20-42
As you can see the is not the contact form in the code that you submitted

**Comment by DanielAD10** [comment]
Hello @LionRouge1, I'm sorry. I will do the change.

**Review by emmiiorji — APPROVED** [review]
Hi @DanielAD10 and Team, 

# Status: Approved ✅

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<div align='center'>

</div>

## Good Highlights✔️

- Requested changes have been implemented

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
